version: "2.1"
   
services:
  octoprint:
    image: "rpiforge/octoprint:latest"
    container_name: octoprint
    restart: unless-stopped
    devices:
      - /dev/ttyAMA0:/dev/ttyAMA0
    ports:
      - "5000:5000"

  companion:
    image: "rpiforge/companion:latest"
    container_name: companion
    restart: unless-stopped
    depends_on:
      - octoprint
    environment:
      - OCTOPRINT_IP=octoprint
      - BUFFER_LOC=/data/data.hdf5

volumes:
    influx-data:
      driver: local
